### ISSUE TITLE
The bot wont accept my "/settings upload" tried several methods

### ISSUE THREAD

**Issue by KuroDonut** [HarutoHiroki/Discord.js-Bot#12]
It wont let me give the file it gives me an error which i read but didn't understand

`Done Downloading
(node:15940) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token | in JSON at position 66
    at JSON.parse (<anonymous>)
    at WriteStream.<anonymous> (C:\Users\Gamma\Desktop\Discord.js-Bot\commands\settings.js:24:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:15940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15940) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by HarutoHiroki** [comment]
SyntaxError: Unexpected token | in JSON at position 66
how about you can try !settings example to see how you SHOULD be configuring your JSON file since this bot need you to understand how a JSON works
