### ISSUE TITLE
Can't seem to get hte bot working I think i did something wrong

### ISSUE THREAD

**Issue by KuroDonut** [HarutoHiroki/Discord.js-Bot#5]
The bot wont work perhaps i did something wrong?, Please help me out

Error code:
	Error: Cannot find module './settings.json'
Require stack:
- C:\Users\Gamma\Downloads\Ny mapp\Discord.js-Bot\events\guildCreate.js
- C:\Users\Gamma\Downloads\Ny mapp\Discord.js-Bot\util\eventLoader.js
- C:\Users\Gamma\Downloads\Ny mapp\Discord.js-Bot\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Gamma\Downloads\Ny mapp\Discord.js-Bot\events\guildCreate.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at reqEvent (C:\Users\Gamma\Downloads\Ny mapp\Discord.js-Bot\util\eventLoader.js:1:29)
    at module.exports (C:\Users\Gamma\Downloads\Ny mapp\Discord.js-Bot\util\eventLoader.js:7:28)
    at Object.<anonymous> (C:\Users\Gamma\Downloads\Ny mapp\Discord.js-Bot\index.js:9:30)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Gamma\\Downloads\\Ny mapp\\Discord.js-Bot\\events\\guildCreate.js',
    'C:\\Users\\Gamma\\Downloads\\Ny mapp\\Discord.js-Bot\\util\\eventLoader.js',
    'C:\\Users\\Gamma\\Downloads\\Ny mapp\\Discord.js-Bot\\index.js'
  ]
}
PS C:\Users\Gamma\Downloads\Ny mapp\Discord.js-Bot>

**Comment by HarutoHiroki** [comment]
as the error message stated it can't find your settings.json file and that's why it doesn't work. Hope this helps you
