### ISSUE TITLE
when i start the bot this comes up, i really like the bot and tried to fix this serveral times but doesnt work

### ISSUE THREAD

**Issue by EkamAujla** [HarutoHiroki/Discord.js-Bot#7]
****Error: Cannot find module './settings.json'
Require stack:
- C:\Users\gunve\Desktop\Discord.js-Bot-master\events\guildCreate.js
- C:\Users\gunve\Desktop\Discord.js-Bot-master\util\eventLoader.js
- C:\Users\gunve\Desktop\Discord.js-Bot-master\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\gunve\Desktop\Discord.js-Bot-master\events\guildCreate.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at reqEvent (C:\Users\gunve\Desktop\Discord.js-Bot-master\util\eventLoader.js:1:29)
    at module.exports (C:\Users\gunve\Desktop\Discord.js-Bot-master\util\eventLoader.js:7:28)
    at Object.<anonymous> (C:\Users\gunve\Desktop\Discord.js-Bot-master\index.js:9:30)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\gunve\\Desktop\\Discord.js-Bot-master\\events\\guildCreate.js',
    'C:\\Users\\gunve\\Desktop\\Discord.js-Bot-master\\util\\eventLoader.js',
    'C:\\Users\\gunve\\Desktop\\Discord.js-Bot-master\\index.js****

**Comment by HarutoHiroki** [comment]
the bot cant find your settings.json file which has everything from tokens to prefix and your owner ID, make sure the folder has the file before running the bot

**Comment by EkamAujla** [comment]
I have set it up but it still doesn't detect it,it exactly as it should be.please please help me...where should i place it?

**Comment by HarutoHiroki** [comment]
in the main folder

**Comment by EkamAujla** [comment]
Activities.json is missing in data folder

**Comment by EkamAujla** [comment]
The bot is 100% up but doesnt respond to commands(i had to remove activities.json requirement)

**Comment by HarutoHiroki** [comment]
bugs are fixed in the latest push

**Comment by EkamAujla** [comment]
It still doesn't respond to ANY of the command😓
